# Generated by Django 3.0.8 on 2020-08-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
