# Generated by Django 3.0.8 on 2020-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
