# Generated by Django 3.0.8 on 2020-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0003_write_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='image',
            field=models.ImageField(default='ootdapp/defaultimage/ho.jpg', upload_to='images/'),
        ),
    ]
